// Generated by the Blazor I18n Text compiler
namespace Web1Apps.I18nText
{
    public partial class MyText : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Counter"</summary>
        public string SidebarCounter;

        /// <summary>"Fetch Data"</summary>
        public string SidebarFetch;

        /// <summary>"Home"</summary>
        public string SidebarHome;

        /// <summary>"Welcome to your new app."</summary>
        public string WelcomePage;
    }
}
